ALTER TYPE "MovementType" ADD VALUE IF NOT EXISTS 'ADJUSTMENT_IN';
ALTER TYPE "MovementType" ADD VALUE IF NOT EXISTS 'ADJUSTMENT_OUT';

ALTER TABLE "stock_movements" ADD COLUMN IF NOT EXISTS "note" TEXT;
