ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SALES';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'WAREHOUSE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ACCOUNTING';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VIEWER';
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'VIEWER';
